from typing import Tuple, overload

_Shape = Tuple[int, ...]
__doc__: str

class vec3:
    x: float
    y: float
    z: float

    @overload
    def __init__(vec: vec3) -> vec3: ...
    @overload
    def __init__(vec: tuple[float, float, float]) -> vec3: ...
    @overload
    def __init__(x: float=0, y: float=0, z: float=0) -> vec3: ...
    def __getitem__(self, i: int) -> float: ...
    def __setitem__(self, i: int, value: float) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: vec3) -> bool: ...
    def __ne__(self, other: vec3) -> bool: ...
